=head1 The Raku Infrastructure Documentation Repo

Here we try to document how infrastructure in and around the Raku community
is set up, and who maintains it.

Nicknames in documents in here usually refer to IRC nicknames used on
L<#raku|http://raku.org/community/irc>, or alternatively to github user
names.

