=head1 www.p6c.org - Perl 6 community web server

www.p6c.org is a community server, with the hardware donated by the
community, and the server generously hosted by
L<noris network AG|http://noris.de/>.

It hosts Perl 6-related web sites, including L<http://perl6.org> and most of
its subdomains (the sole exception being L<http://testers.perl6.org>), as well
as L<http://ecosystem-api.p6c.org>.

The perl6.org subdomains are also available as C<subdomain.p6c.org>. (This was
mostly used for testing the sites before the perl6.org DNS pointed to the
server, but can be (ab)used for other purposes, which require more control
over the DNS).

=head2 Network

IPv4 address: 213.95.82.53

IPv6 addresses: 2001:780:101:ff00::80:1 to 2001:780:101:ff00::80:9.

(The complete block 2001:780:101:ff00::80:1 to 2001:780:101:ff00::80:ffff is
available for this host, the addresses just aren't all bound to the interface
yet).

    perlcabal.org       2001:780:101:ff00::80:2
    design.perl6.org    2001:780:101:ff00::80:3
    rakudo.org          2001:780:101:ff00::80:A

=head2 Websites

Each (sub)domain that's hosted on www.p6c.org has its own UNIX user, with the
same name as the domain. So for example for L<http://modules.perl6.org>
there's a user C<modules.perl6.org> with home C</home/modules.perl6.org>. In
the home directory there's typically a checkout of the git repository that
contains the sources for the website, and often a script (typically C<update.sh>)
that generates or copies the actual site, e.g. C</var/www/faq.perl6.org/>.

Note that the content for several websites gets built on
L<< C<hack.p6c.org>|hack.p6c.org.pod >> and then copied over to C<www.p6c.org>.

The users's crontab contains a line that calls the script, typically once per
hour:

    root@www:~# sudo -iu faq.perl6.org crontab -l|grep -vE '^#'
    */15    *       *       *       *       cd ~/faq; git pull -qfn; perl generate-web.pl /var/www/faq.perl6.org/

In the case of L<http://doc.perl6.org/> and L<http://examples.perl6.org>,
the cron job runs on the host C<hack.p6c.org>.

=head2 Administration

The following users have root/sudo access, and can potentially help you:

  username      IRC nick
  ========      ========
  moritz        moritz
  timo          timotimo
  froggs        FROGGS
  coke          [Coke]      (has sudo privs)
  zoffix        Zoffix      (has sudo privs and also the key in root user)

Selected files under C</etc> are under version control with git; if you change
a file under C</etc>, please add and commit it:

    cd /etc/
    git add -f path/to/file
    git commit --author='Your Name <email@example.com>' -m 'configured the flurb'

=head2 modules.perl6.org

=head3 Restarting the web app

The app gets started automatically on server reboot as well as after database is
updated (a cronjob that takes ~1.5hr runs on 20th and 50th minute of the hour).

If it happens that you need to manually restart the web app, you can do so by running:

    su - modules.perl6.org
    cd ~/modules.perl6.org/
    hypnotoad bin/ModulesPerl6.pl

A development server can be started to produce more output to debug some issues by running:

    su - modules.perl6.org
    cd ~/modules.perl6.org/
    bin/morbo

=head2 rakudo.org

Site uses C<rakudo> user and the L<repo|https://github.com/perl6/rakudo.org/>'s checkout 
lives in C</var/www/rakudo.perl6.org/rakudo.org>. A cronjob runs
C</var/www/rakudo.perl6.org/rakudo.org/update-rakudo.org.sh> script every 5 minutes.
On reboot, cron runs C</var/www/rakudo.perl6.org/rakudo.org/start-rakudo.org.sh>

=head2 marketing.perl6.org

Site uses C<marketing> user and the L<repo|https://github.com/perl6/marketing/>'s checkout 
lives in C</home/marketing/marketing>. A cronjob runs
C</home/marketing/marketing/update-marketing.perl6.org.sh> script every 5 minutes.
On reboot, cron runs C</home/marketing/marketing/start-marketing.perl6.org.sh>

=head3 Restarting the web app

If for whatever reason cron doesn't start the app, you can start it by running C<./hyp>
in C</var/www/rakudo.perl6.org/rakudo.org>. The web app listens on port C<4242>, with
Apache reverse proxy setup in C</etc/apache2/sites-available/rakudo.org.conf>
(note: there's a ton of URL rewrites there).
